-- Convert DATETIME columns to TIMESTAMP for proper UTC handling
-- TIMESTAMP stores values in UTC and sqlx decodes them as DateTime<Utc>

-- Workers table
ALTER TABLE workers MODIFY COLUMN last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
ALTER TABLE workers MODIFY COLUMN started_at TIMESTAMP NULL;

-- Jobs table
ALTER TABLE jobs MODIFY COLUMN run_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE jobs MODIFY COLUMN lock_at TIMESTAMP NULL;
ALTER TABLE jobs MODIFY COLUMN done_at TIMESTAMP NULL;
